bate_papo_user:
    resource: "@BatePapoUserBundle/Controller"
    type:     annotation
    prefix:   /

bate_papo_base:
    resource: "@BatePapoBaseBundle/Controller"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"